
enum ActionTypes {
    FETCH_PRODUCT_LIST = 'eAuction/FETCH_PRODUCT_LIST',
    FETCH_PRODUCT_LIST_SUCCESS = 'eAuction/FETCH_PRODUCT_LIST_SUCCESS',
    FETCH_PRODUCT_LIST_ERROR = 'eAuction/FETCH_PRODUCT_LIST_ERROR',

    FETCH_PRODUCT_DETAILS = 'eAuction/FETCH_PRODUCT_DETAILS',
    FETCH_PRODUCT_DETAILS_SUCCESS = 'eAuction/FETCH_PRODUCT_DETAILS_SUCCESS',
    FETCH_PRODUCT_DETAILS_ERROR = 'eAuction/FETCH_PRODUCT_DETAILS_ERROR',
  }
  
  export default ActionTypes;
